"""Primera migracion

Revision ID: 45c332966d58
Revises: 
Create Date: 2025-06-05 19:35:55.999303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c332966d58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id_especie', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_especie'),
    sa.UniqueConstraint('especie')
    )
    op.create_index(op.f('ix_especies_id_especie'), 'especies', ['id_especie'], unique=False)
    op.create_table('perfil_adopcion',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('tipo_vivienda', sa.String(length=50), nullable=True),
    sa.Column('familia', sa.Text(), nullable=True),
    sa.Column('mascota', sa.Boolean(), nullable=True),
    sa.Column('dedicacion', sa.Text(), nullable=True),
    sa.Column('tiempo_libre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_perfil')
    )
    op.create_index(op.f('ix_perfil_adopcion_id_perfil'), 'perfil_adopcion', ['id_perfil'], unique=False)
    op.create_table('razas',
    sa.Column('id_raza', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_raza'),
    sa.UniqueConstraint('raza')
    )
    op.create_index(op.f('ix_razas_id_raza'), 'razas', ['id_raza'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('rol')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('nombre_mascota', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('id_especie', sa.Integer(), nullable=True),
    sa.Column('id_raza', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('estado_mascota', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('fecha_regreso', sa.Date(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_especie'], ['especies.id_especie'], ),
    sa.ForeignKeyConstraint(['id_raza'], ['razas.id_raza'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mascota')
    )
    op.create_index(op.f('ix_mascotas_id_mascota'), 'mascotas', ['id_mascota'], unique=False)
    op.create_table('adopciones',
    sa.Column('id_adopcion', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('id_mascota', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('estado_adopcion', sa.String(length=20), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_entrevista', sa.Date(), nullable=True),
    sa.Column('id_entrevistador', sa.Integer(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrevistador'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_adopcion.id_perfil'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_adopcion')
    )
    op.create_index(op.f('ix_adopciones_id_adopcion'), 'adopciones', ['id_adopcion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adopciones_id_adopcion'), table_name='adopciones')
    op.drop_table('adopciones')
    op.drop_index(op.f('ix_mascotas_id_mascota'), table_name='mascotas')
    op.drop_table('mascotas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_razas_id_raza'), table_name='razas')
    op.drop_table('razas')
    op.drop_index(op.f('ix_perfil_adopcion_id_perfil'), table_name='perfil_adopcion')
    op.drop_table('perfil_adopcion')
    op.drop_index(op.f('ix_especies_id_especie'), table_name='especies')
    op.drop_table('especies')
    # ### end Alembic commands ###
