"""Descripcion de mascota

Revision ID: a47b18155e9b
Revises: e6abdc57d409
Create Date: 2025-06-23 12:10:52.711631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47b18155e9b'
down_revision: Union[str, None] = 'e6abdc57d409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especies', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('especies_especie_key'), 'especies', type_='unique')
    op.create_unique_constraint(None, 'especies', ['nombre'])
    op.drop_column('especies', 'especie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especies', sa.Column('especie', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'especies', type_='unique')
    op.create_unique_constraint(op.f('especies_especie_key'), 'especies', ['especie'], postgresql_nulls_not_distinct=False)
    op.drop_column('especies', 'nombre')
    # ### end Alembic commands ###
