"""Descripcion de mascota

Revision ID: aadf8ee60cc1
Revises: a47b18155e9b
Create Date: 2025-06-23 12:13:57.131396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadf8ee60cc1'
down_revision: Union[str, None] = 'a47b18155e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('razas', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.drop_column('razas', 'raza')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('razas', sa.Column('raza', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('razas', 'nombre')
    # ### end Alembic commands ###
