"""mueve correo de persona a usuario

Revision ID: e5d8c48367d1
Revises: aadf8ee60cc1
Create Date: 2025-07-01 21:45:06.222922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d8c48367d1'
down_revision: Union[str, None] = 'aadf8ee60cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Elimina la columna de personas si existe
    with op.batch_alter_table('personas') as batch_op:
        batch_op.drop_column('correo')
    # Agrega la columna a usuarios como nullable
    op.add_column('usuarios', sa.Column('correo', sa.String(length=100), unique=True, nullable=True))
    # Rellena los valores con correos temporales
    op.execute("""
        UPDATE usuarios
        SET correo = 'sin_correo_' || id_usuario || '@ejemplo.com'
        WHERE correo IS NULL OR correo = ''
    """)
    # Ahora sí, haz la columna NOT NULL
    op.alter_column('usuarios', 'correo', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'correo')
    # ### end Alembic commands ###
