"""Agrega tabla fotos_mascota y relación con mascota

Revision ID: e68976838202
Revises: 52c8a3e5190c
Create Date: 2025-06-11 18:03:24.213034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68976838202'
down_revision: Union[str, None] = '52c8a3e5190c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_mascota',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_index(op.f('ix_fotos_mascota_id_foto'), 'fotos_mascota', ['id_foto'], unique=False)
    op.drop_column('mascotas', 'foto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('foto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fotos_mascota_id_foto'), table_name='fotos_mascota')
    op.drop_table('fotos_mascota')
    # ### end Alembic commands ###
