"""Descripcion de mascota

Revision ID: e6abdc57d409
Revises: e68976838202
Create Date: 2025-06-23 12:02:45.590219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6abdc57d409'
down_revision: Union[str, None] = 'e68976838202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('descripcion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mascotas', 'descripcion')
    # ### end Alembic commands ###
